services:
  mosquito:
    container_name: mosquito-${ENV}
    image: eclipse-mosquitto
    mem_limit: 100m
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${MOSQUITO_CONFIG_FOLDER}/config/:/mosquitto/config/
      - ${MOSQUITO_CONFIG_FOLDER}/log/:/mosquitto/log/
    networks:
      spa-network:
        ipv4_address: 172.22.3.10
  db-mongo:
    container_name: mongo-${ENV}
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '60017:27017'
    networks:
      spa-network:
        ipv4_address: 172.22.3.11
  app:
    container_name: app-back-${ENV}
    image: loicpincon/spa-intex-back:${VERSION_BACK}
    ports:
      - 6500:6500
    environment:
      - MQTT_HOSTNAME=${MQTT_HOSTNAME}
      - MQTT_USERNAME=${MQTT_USERNAME_BACK}
      - MQTT_PASSWORD=${MQTT_PASSWORD_BACK}
      - MQTT_PORT=${MQTT_PORT}
      - SPRING_DATA_MONGODB_HOST=${SPRING_DATA_MONGODB_HOST}
      - SPRING_DATA_MONGODB_PORT=${SPRING_DATA_MONGODB_PORT}
      - SPRING_DATA_MONGODB_USERNAME=${SPRING_DATA_MONGODB_USERNAME}
      - SPRING_DATA_MONGODB_PASSWORD=${SPRING_DATA_MONGODB_PASSWORD}
      - SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE}
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
    networks:
      spa-network:
        ipv4_address: 172.22.3.9
    depends_on:
      - mosquito
      - db-mongo
  front:
    container_name: app-front-${ENV}
    image: loicpincon/spa-intex-front:${VERSION_FRONT}
    ports:
      - 80:80
    networks:
      spa-network:
        ipv4_address: 172.22.3.15
    depends_on:
      - app
networks:
  spa-network:
    driver: bridge
    name: spa-network-${ENV}
    ipam:
      config:
        - subnet: 172.22.3.0/24
