services:
  mosquito:
    container_name: moqsuito
    image: eclipse-mosquitto
    mem_limit: 100m
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/log/:/mosquitto/log/
    networks:
      spa-network:
        ipv4_address: 172.22.3.10
  db-mongo:
    container_name: mongo-dev
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=spaintex
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '60017:27017'
    networks:
      spa-network:
        ipv4_address: 172.22.3.11
  app:
    container_name: app
    image: loicpincon/spa-intex-back:2.0
    ports:
      - 6500:6500
    networks:
      spa-network:
        ipv4_address: 172.22.3.9
    depends_on:
      - mosquito
      - db-mongo
  front:
    container_name: front
    image: loicpincon/spa-intex-front:2.0
    ports:
      - 80:80
    networks:
      spa-network:
        ipv4_address: 172.22.3.15
    depends_on:
      - app
networks:
  spa-network:
    driver: bridge
    name: spa-network
    ipam:
      config:
        - subnet: 172.22.3.0/24
