services:
  mosquito:
    container_name: moqsuito
    image: eclipse-mosquitto
    mem_limit: 100m
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/log/:/mosquitto/log/
  db:
    container_name: mongo-dev
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '60017:27017'
    volumes:
      - ./data:/data/db
  app:
    container_name: app
    image: loic-app
    ports:
      - 8080:6500
    mem_limit: 100m