server:
  port: 6500
spring:
  data:
    mongodb:
      host: 172.22.3.11
      port: 60017
      username: admin
      password: pass
      authentication-database: admin
      database: spa-intex
mqtt:
  automaticReconnect: true
  cleanSession: true
  connectionTimeout: 10
  clientId: app-cible
  hostname: 172.22.3.10
  port: 1883
  username: spa
  password: spa


